version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php7
    container_name: "nginx-php"
    depends_on:
      - db
    ports:
      - 80:80
      - 81:81
    volumes:
      - /var/www:/var/www
    links:
      - db:database
    privileged: true
  db:
    image: "mysql:5.6.25"
    container_name: "test-db"
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
